services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 10.200.1.3:3000
      HOMEPAGE_KUMA_URL: http://localhost:3001
      LOG_LEVEL: debug

  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: always
    cap_add:
      - NET_RAW
    ports:
      - 3002:8080
    volumes:
      - ./gatus:/config

  py-proxy:
    build: ./py-proxy/
    container_name: py-proxy
    restart: unless-stopped
    ports:
      - "5000:5000" # no external traffic
    environment:
      - GATUS_URL=http://10.200.1.3:3002/api/v1/endpoints/statuses
