services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./homepage/icons:/app/public/icons
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
      LOG_LEVEL: debug

  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: unless-stopped
    cap_add:
      - NET_RAW
    ports:
      - 3002:8080
    volumes:
      - ./gatus:/config

  py-proxy:
    build: ./py-proxy/
    container_name: py-proxy
    restart: unless-stopped
    ports:
      - "5000:5000" # no external traffic
    environment:
      - GATUS_URL=${GATUS_URL}