endpoints:
##########################################
### General
##########################################
  # - name: template HTTP website
  #   group: core
  #   url: "http://x.x.x.x:xxxx"
  #   interval: xxs
  #   conditions:
  #     - "[STATUS] == 200"

  # - name: template open TCP port
  #   group: core
  #   url: "tcp://x.x.x.x:22"
  #   interval: xxs
  #   conditions:
  #     - "[CONNECTED] == true"

  - name: Cisco Switch
    group: core
    url: "icmp://10.200.1.2"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Uptime Server - Kuma
    group: core
    url: "http://10.200.1.3:3001"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Uptime Server - Homepage
    group: core
    url: "http://10.200.1.3:3000"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Uptime Server - Gatus
    group: core
    url: "http://10.200.1.3:3002"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: ESXI Server
    group: core
    url: "https://10.200.1.10:443"
    client:
      insecure: true
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: TrueNAS Admin Webpage
    group: core
    url: "https://10.200.1.11"
    client:
      insecure: true # disables SSL verfication
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: TrueNAS SMB Shares
    group: core
    url: "tcp://10.200.1.11:445"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Proxmox
    group: core
    url: "icmp://10.200.1.15"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Proxmox (ILO)
    group: core
    url: "icmp://10.200.1.20"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: CTRE
    group: core
    url: "icmp://10.200.1.16"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Extra Dev Box
    group: core
    url: "tcp://10.200.1.18:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Emile's File Server SSH
    group: core
    url: "tcp://10.200.1.19:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Emile's File Server Syncthing
    group: core
    url: "tcp://10.200.1.19:22000"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: devine
    group: core
    url: "http://10.200.1.50:3000/api/health"
    interval: 60s
    conditions:
      - "[STATUS] == 200"


##########################################
### Challenges
##########################################
  - name: Tryouts c01
    group: challs
    url: "icmp://10.200.1.101"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Tryouts c02
    group: challs
    url: "icmp://10.200.1.102"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Tryouts c03
    group: challs
    url: "tcp://10.200.1.103:4212"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Tryouts c04
    group: challs
    url: "http://10.200.1.104:8084"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Tryouts c05
    group: challs
    url: "http://10.200.1.104:8085"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Tryouts c06
    group: challs
    url: "http://10.200.1.104:8086"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Tryouts c07
    group: challs
    url: "http://10.200.1.104:8087"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Tryouts c08
    group: challs
    url: "http://10.200.1.104:8088"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Tryouts c09
    group: challs
    url: "http://10.200.1.104:8089"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Tryouts c10
    group: challs
    url: "http://10.200.1.104:8090"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: Tryouts c15
    group: challs
    url: "tcp://10.200.1.106:1337"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Tryouts c16
    group: challs
    url: "icmp://10.200.1.105"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

  - name: Tryouts c17
    group: challs
    url: "http://10.200.1.106:80"
    interval: 60s
    conditions:
      - "[STATUS] == 200"

  - name: CCX Scoreboard HTTP
    group: challs
    url: "http://10.200.1.30:80"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: CCX Scoreboard SSH
    group: challs
    url: "tcp://10.200.1.30:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: CCX Router
    group: challs
    url: "icmp://10.200.1.25"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: CCX Kali T1
    group: challs
    url: "tcp://10.200.1.31:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: CCX Kali T2
    group: challs
    url: "tcp://10.200.1.32:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: CCX Kali T3
    group: challs
    url: "tcp://10.200.1.33:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: CCX CTFd HTTPS
    group: challs
    url: "https://10.200.1.34:443"
    client:
      insecure: true
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: CCX CTFd SSH
    group: challs
    url: "tcp://10.200.1.34:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Flask Security CTF Host 1
    group: challs
    url: "http://10.200.1.41:5000"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: Flask Security CTF Host 2
    group: challs
    url: "http://10.200.1.42:5000"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: Flask Security CTF Host 3
    group: challs
    url: "http://10.200.1.43:5000"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: Flask Security CTF Host 4
    group: challs
    url: "http://10.200.1.44:5000"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: Flask Security CTF Host 5
    group: challs
    url: "http://10.200.1.45:5000"
    interval: 60s
    conditions:
      - "[STATUS] == 200"


##########################################
### Capstones
##########################################
  - name: Dev Workstation
    group: Capstone
    url: "tcp://10.200.1.12:5900"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Clickhouse DB WebUI
    group: Capstone
    url: "http://10.200.1.13:8123"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: Clickhouse DB MySQL
    group: Capstone
    url: "tcp://10.200.1.13:3306"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Clickhouse DB SSH
    group: Capstone
    url: "tcp://10.200.1.13:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Clickhouse DB Clickhouse Server
    group: Capstone
    url: "tcp://10.200.1.13:9000"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Clickhouse DB Clickhouse Replication
    group: Capstone
    url: "tcp://10.200.1.13:9009"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Clickhouse DBV2 SSH
    group: Capstone
    url: "tcp://10.200.1.22:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Clickhouse DBV2 Clickhouse Server
    group: Capstone
    url: "tcp://10.200.1.22:9000"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Clickhouse DBV2 WebUI
    group: Capstone
    url: "http://10.200.1.22:8123"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: GitLab Server Webpage
    group: Capstone
    url: "http://10.200.1.14:80"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: GitLab Server SSH
    group: Capstone
    url: "tcp://10.200.1.13:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Shadow's Edge
    group: Capstone
    url: "icmp://10.200.1.107"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

##########################################
### CCDC
##########################################
  - name: HTTP
    group: CCDC
    url: "http://10.200.1.30:80"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
  - name: SMTP
    group: CCDC
    url: "tcp://10.200.1.30:25"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: DNS
    group: CCDC
    url: "udp://10.200.1.30:53"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: SSH
    group: CCDC
    url: "tcp://10.200.1.30:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Git
    group: CCDC
    url: "tcp://10.200.1.30:3000"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: RedTeam-SSH
    group: CCDC
    url: "tcp://10.200.1.22:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: RedTeam-Listener
    group: CCDC
    url: "tcp://10.200.1.22:4444"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"

##########################################
### JUMP BOXES
##########################################
### J1
  - name: Jump Box 1 SSH
    group: core
    url: "tcp://10.200.1.35:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 1-1
    group: core
    url: "tcp://10.200.1.35:5901"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 1-2
    group: core
    url: "tcp://10.200.1.35:5902"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 1-3
    group: core
    url: "tcp://10.200.1.35:5903"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 1-4
    group: core
    url: "tcp://10.200.1.35:5904"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 1-5
    group: core
    url: "tcp://10.200.1.35:5905"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 1-6
    group: core
    url: "tcp://10.200.1.35:5906"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
### J2
  - name: Jump Box 2 SSH
    group: core
    url: "tcp://10.200.1.36:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 2-1
    group: core
    url: "tcp://10.200.1.36:5901"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 2-2
    group: core
    url: "tcp://10.200.1.36:5902"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 2-3
    group: core
    url: "tcp://10.200.1.36:5903"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 2-4
    group: core
    url: "tcp://10.200.1.36:5904"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 2-5
    group: core
    url: "tcp://10.200.1.36:5905"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 2-6
    group: core
    url: "tcp://10.200.1.36:5906"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
### J3
  - name: Jump Box 3 SSH
    group: core
    url: "tcp://10.200.1.37:22"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 3-1
    group: core
    url: "tcp://10.200.1.37:5901"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 3-2
    group: core
    url: "tcp://10.200.1.37:5902"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 3-3
    group: core
    url: "tcp://10.200.1.37:5903"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 3-4
    group: core
    url: "tcp://10.200.1.37:5904"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 3-5
    group: core
    url: "tcp://10.200.1.37:5905"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
  - name: Jump Box 3-6
    group: core
    url: "tcp://10.200.1.37:5906"
    interval: 60s
    conditions:
      - "[CONNECTED] == true"
