- Network Stack & Hardware:
    - Cisco Switch:
        icon: cisco
        description: "10.200.1.2"
        href: http://10.200.1.2
        ping: 10.200.1.2
    - Uptime Server:
        icon: uptime-kuma
        description: "10.200.1.3"
        href: http://10.200.1.3:3000/
        ping: 10.200.1.3
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              refreshInterval: 10000
              mappings:
                - field: "core_uptime-server---homepage.online"
                  label: "Homepage (:3000)"
                  format: text
                - field: "core_uptime-server---gatus.online"
                  label: "Gatus (:3002)"
                  format: text

    - ESXI Server:
        icon: vmware
        description: "10.200.1.10"
        href: https://10.200.1.10/
        ping: 10.200.1.10
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_esxi-server.online"
                  label: "Webpage (:443)"
                  format: text

    - TrueNas:
        icon: truenas
        description: "10.200.1.11"
        href: http://10.200.1.11/
        ping: 10.200.1.11
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_truenas-admin-webpage.online"
                  label: "Webpage (:443)"
                  format: text
                - field: "core_truenas-smb-shares.online"
                  label: "SMB (:445)"
                  format: text

    - Proxmox:
        icon: proxmox
        description: "10.200.1.15"
        ping: 10.200.1.15
    - Proxmox (ILO):
        icon: proxmox
        description: "10.200.1.20"
        ping: 10.200.1.20
    - CTRE:
        icon: terraform
        description: "10.200.1.16"
        ping: 10.200.1.16

    - Extra Dev Box:
        icon: ubuntu-linux
        description: "10.200.1.18"
        ping: 10.200.1.18
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_extra-dev-box.online"
                  label: "SSH (:22)"
                  format: text

    - Emile's File Server:
        icon: files
        description: "10.200.1.19"
        ping: 10.200.1.19
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_emile's-file-server-ssh.online"
                  label: "SSH (:22)"
                  format: text
                - field: "core_emile's-file-server-syncthing.online"
                  label: "Syncthing (:22000)"
                  format: text

    - devine:
        icon: openai
        description: "10.200.1.50"
        ping: 10.200.1.50
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_devine.online"
                  label: "HTTP (:3000)"
                  format: text

    - Jump Box 1:
        icon: microsoft-remote-desktop
        description: "10.200.1.35"
        ping: 10.200.1.35
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_jump-box-1-ssh.online"
                  label: "SSH (:22)"
                  format: text
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_jump-box-1-1.online"
                  label: "User 1 (:5901)"
                  format: text
                - field: "core_jump-box-1-2.online"
                  label: "User 2 (:5902)"
                  format: text
                - field: "core_jump-box-1-3.online"
                  label: "User 3 (:5903)"
                  format: text
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_jump-box-1-4.online"
                  label: "User 4 (:5904)"
                  format: text
                - field: "core_jump-box-1-5.online"
                  label: "User 5 (:5905)"
                  format: text
                - field: "core_jump-box-1-6.online"
                  label: "User 6 (:5906)"
                  format: text

    - Jump Box 2:
        icon: microsoft-remote-desktop
        description: "10.200.1.36"
        ping: 10.200.1.36
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_jump-box-2-ssh.online"
                  label: "SSH (:22)"
                  format: text
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_jump-box-2-1.online"
                  label: "User 1 (:5901)"
                  format: text
                - field: "core_jump-box-2-2.online"
                  label: "User 2 (:5902)"
                  format: text
                - field: "core_jump-box-2-3.online"
                  label: "User 3 (:5903)"
                  format: text
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_jump-box-2-4.online"
                  label: "User 4 (:5904)"
                  format: text
                - field: "core_jump-box-2-5.online"
                  label: "User 5 (:5905)"
                  format: text
                - field: "core_jump-box-2-6.online"
                  label: "User 6 (:5906)"
                  format: text
    
    - Jump Box 3:
        icon: microsoft-remote-desktop
        description: "10.200.1.37"
        ping: 10.200.1.37
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_jump-box-3-ssh.online"
                  label: "SSH (:22)"
                  format: text
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_jump-box-3-1.online"
                  label: "User 1 (:5901)"
                  format: text
                - field: "core_jump-box-3-2.online"
                  label: "User 2 (:5902)"
                  format: text
                - field: "core_jump-box-3-3.online"
                  label: "User 3 (:5903)"
                  format: text
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "core_jump-box-3-4.online"
                  label: "User 4 (:5904)"
                  format: text
                - field: "core_jump-box-3-5.online"
                  label: "User 5 (:5905)"
                  format: text
                - field: "core_jump-box-3-6.online"
                  label: "User 6 (:5906)"
                  format: text


- Challenges and Labs:
    - CCX Scoreboard:
        icon: /icons/ncx.jpeg
        description: 10.200.1.30
        ping: 10.200.1.30
        href: http://10.200.1.30:80
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "challs_ccx-scoreboard-http.online"
                  label: "flask (:80)"
                  format: text
                - field: "challs_ccx-scoreboard-ssh.online"
                  label: "SSH (:22)"
                  format: text
    - "CCX Router":
        icon: opnsense
        description: 10.200.1.25
    - "CCX Kali Team 1":
        icon: kali-linux
        description: 10.200.1.31
        ping: 10.200.1.31
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "challs_ccx-kali-t1.online"
                  label: "SSH (:22)"
                  format: text
    - "CCX Kali Team 2":
        icon: kali-linux
        description: 10.200.1.32
        ping: 10.200.1.32
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "challs_ccx-kali-t2.online"
                  label: "SSH (:22)"
                  format: text
    - "CCX Kali Team 3":
        icon: kali-linux
        description: 10.200.1.33
        ping: 10.200.1.33
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "challs_ccx-kali-t3.online"
                  label: "SSH (:22)"
                  format: text
    - CCX CTFd Instance:
        icon: /icons/ncx.jpeg
        description: 10.200.1.34
        ping: 10.200.1.34
        href: https://10.200.1.34:443
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "challs_ccx-ctfd-https.online"
                  label: "CTFd (:443)"
                  format: text
                - field: "challs_ccx-ctfd-ssh.online"
                  label: "SSH (:22)"
                  format: text
    - SoftDev Flask CTF Host 1:
        icon: python
        description: 10.200.1.41
        ping: 10.200.1.41
        href: http://10.200.1.41:5000
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "challs_flask-security-ctf-host-1.online"
                  label: "Flask CTF Hub (:5000)"
                  format: text
    - SoftDev Flask CTF Host 2:
        icon: python
        description: 10.200.1.42
        ping: 10.200.1.42
        href: http://10.200.1.42:5000
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "challs_flask-security-ctf-host-2.online"
                  label: "Flask CTF Hub (:5000)"
                  format: text
    - SoftDev Flask CTF Host 3:
        icon: python
        description: 10.200.1.43
        ping: 10.200.1.43
        href: http://10.200.1.43:5000
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "challs_flask-security-ctf-host-3.online"
                  label: "Flask CTF Hub (:5000)"
                  format: text


    - PA Firewall :
        icon: palo-alto
        description: 10.200.1.21
    - "Tryouts c16":
        icon: terminal
        description: 10.200.1.105
        ping: 10.200.1.105


- Capstone:
    - Dev Workstation:
        icon: windows-10
        description: 10.200.1.12
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "capstone_dev-workstation.online"
                  label: "VNC (:5900)"
                  format: text

    - Clickhouse DB:
        icon: clickhouse
        description: 10.200.1.13
        ping: 10.200.1.13
        href: http://10.200.1.13:8123
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "capstone_clickhouse-db-ssh.online"
                  label: "SSH (:22)"
                  format: text
                - field: "capstone_clickhouse-db-webui.online"
                  label: "Web (:8123)"
                  format: text
                - field: "capstone_clickhouse-db-clickhouse-server.online"
                  label: "Clickhouse (:9000)"
                  format: text

    - Clickhouse DBV2:
        icon: clickhouse
        description: 10.200.1.22
        ping: 10.200.1.22
        href: http://10.200.1.22:8123
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "capstone_clickhouse-dbv2-ssh.online"
                  label: "SSH (:22)"
                  format: text
                - field: "capstone_clickhouse-dbv2-webui.online"
                  label: "Web (:8123)"
                  format: text
                - field: "capstone_clickhouse-dbv2-clickhouse-server.online"
                  label: "Clickhouse (:9000)"
                  format: text

    - Gitlab Server:
        icon: git
        description: 10.200.1.14
        ping: 10.200.1.14
        href: http://10.200.1.14/
        widgets:
            - type: customapi
              url: http://172.18.0.1:5000/status
              mappings:
                - field: "capstone_gitlab-server-ssh.online"
                  label: "SSH (:22)"
                  format: text
                - field: "capstone_gitlab-server-webpage.online"
                  label: "Webpage (:80)"
                  format: text

    - Shadow's Edge:
        description: 10.200.1.107
        ping: 10.200.1.107


- Competition Schedule:
    - "6-13 Jan: PCUP Individuals Round 1":
        description: Jaden, Neil, Emile, Nick, Ian, and Kaci Qualified for Round 2 in Offensive. Jaden, Emile, and Neil qualified for Round 2 in Defensive Track.
        href: "#"          # Prevents navigation errors if clicked
    - "10 Jan: Mountain West Cyber Challenge":
        description: 1st place (Delogrand), 10th place (Delogrander)
        href: "#"
    - "20-27 Jan: PCUP Teams Round 1":
        description: Jaden, Neil, Emile, Ian, and Tomis qualified for round 2.
        href: "#"
    - "24 Jan: CCDC Regional Qualifier":
        description: "SCA Committee: 1, delogrand: 0" 
        href: "#"
    - "3-10 Feb: PCUP Individual Round 2":
        description: "Jaden, Neil, and Ian qualified for Red Finals. Emile and Neil qualified for Blue Finals. e tan e epi tas."
        href: "#"
    - "17-24 Feb: PCUP Teams Round 2":
        description: "Delogrand qualified for Finals (5th place)"
        href: ""
    - "3-4 Mar: 16AF CTF":
        description: "Drew and Sihu's team won!"
        href: "#"
    - "1-2 Apr: Service Academy Cup":
        description: "Delogrand - 1st Place in Academy cup; Delogrander 1st Place in Open Netwars"
        href: "#"
    - "8-10 Apr: NSA Cyber Exercise":
        description:
        href: "#"
